#SRC += davidlee.c

MOUSEKEY_ENABLE      = yes
KEY_LOCK_ENABLE      = yes
PROGRAMMABLE_BUTTON_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
COMBO_ENABLE         = yes
AUDIO_ENABLE         = yes
CAPS_WORD_ENABLE     = yes
COMMAND_ENABLE       = no
DYNAMIC_MACRO_ENABLE = no
LEADER_ENABLE        = no
AUTO_SHIFT_ENABLE    = no
UNICODE_ENABLE       = no
TAP_DANCE_ENABLE     = no


